[package]
name = "lax"
description = "An command-line argument substitution utility "
homepage = "https://github.com/Property404/lax"
repository = "https://github.com/Property404/lax"
license = "MIT OR Apache-2.0"
version = "0.1.0"
authors = ["Property404 <martinez.dagan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
exec = "0.3.1"
globset = "0.4.6"
walkdir = "2.3.1"

[dev-dependencies]
assert_cmd = "1.0.3"
